### PR TITLE
Change in Your project environment block

### PR DESCRIPTION
**Pull request by Rusllan**
IMAGE=myregistry.com/my-project/image
replaced by base image:
IMAGE=xoelabs/dockery-odoo

### CODE REVIEW

**Comment by blaggacao** [comment]
That's not the idea :-)

**Comment by yelizariev** [comment]
HTML is generated automatically. If you want to change something you need to update source files (not sure which ones)

**Comment by yelizariev** [comment]
Or maybe I'm wrong https://github.com/xoe-labs/dockery-odoo/commit/ef4c73f92a248c778b5e4ed398c0d70962c8f73e

**Comment by blaggacao** [comment]
@yelizariev The workflow is:
Update source, build locally into branch `gh-pages`, which is checked out as a subtree at `public`, then commit and push.
`gh-pages` does not share history with the rest of the repo.

**Comment by yelizariev** [comment]
Then I don't understand why that commit update only html and not some original source

**Comment by blaggacao** [comment]
It's because histories are disconnected. Branch `gh-pages` does not share a single commit with the other branches...

**Comment by yelizariev** [comment]
I got it: doc sources are in ``master`` branch, while ``gh-pages`` has only rendered html. I never organized it like this...

**Pull request closed without merging**
